farmerbb/Taskbar

app/src/main/res/values-ja-land/strings.xml, app/src/main/res/values-ja-port/strings.xml, app/src/main/res/values-ja/strings.xml
=> updated japanese

app/src/androidx86/AndroidManifest.xml
The version in manifest of Android-x86 is not updated.
=> Update version for Android-x86

app/src/compat-27/java/com/farmerbb/taskbar/util/CompatUtils.java
Fix the "WindowManager cannot be resolved to a type" error.
=> Import WindowManager definition

app/src/main/res/values-de/strings.xml
Currently the german translation of the App is quite incomplete. That is quite confusing if some parts are translated and other's not. I fixed that. 
Also there is a spelling mistake in the Notification which tells the user that Taskbar is running. That's realy unpleasant to see all the time and the main reason for this pull request.
I didn't build the app to see if I messed someting up (like escaping special characters) because i currently don't have Android Studio installed on my Laptop, but hopefully it should be fine.
Thanks for this very useful app, especially in combination with SecondScreen.
=> better German translation

app/src/main/java/com/farmerbb/taskbar/util/IconPack.java
Hi, I'm Emanuele Iannone, a master student at University of Salerno.
Since my bachelor's thesis I have been working on a **code smell refactoring plugin** called *aDoctor*, which is able to identify and fix energy-related problems in Android apps.
I launched it on your project, finding different instances of code smells. I chose one of them and let the plugin automatically fix it.
In this case I chose Member Ignoring Method, that is present when a non static method does not use at all instance variables and other non static methods. These kind of smell may have a non trivial impact on energy consumption, as shown in this paper: `https://www.sciencedirect.com/science/article/pii/S0950584918301678`.
Besides, this kind of refactoring does not impact on the functionalities of your app, so it …
=> Refactor Member Ignoring Method smell in IconPack class

app/src/main/res/values-zh-rCN/strings.xml
1. Use origin translation for some specific word, for example "freeform" ->
"自由式".
2. Use SBC case symbol to replace DBC case.
Test it with change the system language to Chinese(zh-cn), and it looks
fine.
=> Add Chinese translation for left string

app/src/main/java/com/farmerbb/taskbar/activity/ContextMenuActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/DashboardActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/HomeActivityDelegate.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivityFreeform.java, app/src/main/java/com/farmerbb/taskbar/activity/KeyboardShortcutActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/MainActivity.java, app/src/main/java/com/farmerbb/taskbar/adapter/StartMenuAdapter.java, app/src/main/java/com/farmerbb/taskbar/content/TaskbarIntent.java, app/src/main/java/com/farmerbb/taskbar/receiver/QuitReceiver.java, app/src/main/java/com/farmerbb/taskbar/receiver/ShowHideTaskbarReceiver.java, app/src/main/java/com/farmerbb/taskbar/ui/DashboardController.java, app/src/main/java/com/farmerbb/taskbar/ui/StartMenuController.java, app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/main/java/com/farmerbb/taskbar/widget/StartMenuLayout.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/TaskerActionReceiver.java
Including those strings:
1. HIDE_START_MENU.
2. TOGGLE_START_MENU.
3. START_MENU_DISAPPEARING.
4. START_MENU_APPEARING.
5. RESET_START_MENU.
6. HIDE_START_MENU_NO_RESET.
7. SHOW/HIDE_START_MENU_SPACE.
=> Extract  *START_MENU* string to TaskbarIntent contants

app/src/main/java/com/farmerbb/taskbar/activity/HomeActivityDelegate.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivityFreeform.java, app/src/main/java/com/farmerbb/taskbar/activity/ShortcutActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/TouchAbsorberActivity.java, app/src/main/java/com/farmerbb/taskbar/content/TaskbarIntent.java, app/src/main/java/com/farmerbb/taskbar/fragment/FreeformModeFragment.java, app/src/main/java/com/farmerbb/taskbar/fragment/SettingsFragment.java, app/src/main/java/com/farmerbb/taskbar/receiver/ToggleFreeformModeReceiver.java, app/src/main/java/com/farmerbb/taskbar/service/NotificationService.java, app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/DisableFreeformReceiver.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/EnableFreeformReceiver.java
Including:
1. UPDATE_FREEFORM_CHECKBOX.
2. FINISH_FREEFORM_ACTIVITY.
3. FREEFORM_PREF_CHANGED.
4. TOGGLE_FREEFORM_MODE.
=> Extract *FREEFORM* string to TaskbarIntent constants

app/src/main/java/com/farmerbb/taskbar/activity/AbstractSelectAppActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/ContextMenuActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/DashboardActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/HomeActivityDelegate.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivityFreeform.java, app/src/main/java/com/farmerbb/taskbar/activity/SelectAppActivity.java, app/src/main/java/com/farmerbb/taskbar/content/TaskbarIntent.java, app/src/main/java/com/farmerbb/taskbar/fragment/FreeformModeFragment.java, app/src/main/java/com/farmerbb/taskbar/service/NotificationService.java, app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/TaskerActionReceiver.java
Including:
1. TEMP_HIDE_TASKBAR.
2. TEMP_SHOW_TASKBAR.
3. SHOW_TASKBAR.
4. FORCE_TASKBAR_RESTART.
5. SHOW_HIDE_TASKBAR.
=> Extract *TASKBAR* string to TaskbarIntent constants

app/src/main/java/com/farmerbb/taskbar/activity/ContextMenuActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivityFreeform.java, app/src/main/java/com/farmerbb/taskbar/content/TaskbarIntent.java, app/src/main/java/com/farmerbb/taskbar/util/U.java
Including:
1. CONTEXT_MENU_APPEARING.
2. CONTEXT_MENU_DISAPPEARING.
3. HIDE_CONTEXT_MENU.
=> Extract *CONTEXT_MENU* to TaskbarIntent constants

app/src/main/java/com/farmerbb/taskbar/activity/ClearDataActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/ContextMenuActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/DashboardActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/DesktopIconSelectAppActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/HomeActivityDelegate.java, app/src/main/java/com/farmerbb/taskbar/activity/ImportSettingsActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/InvisibleActivityFreeform.java, app/src/main/java/com/farmerbb/taskbar/activity/KeyboardShortcutActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/MainActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/ShortcutActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/TouchAbsorberActivity.java, app/src/main/java/com/farmerbb/taskbar/content/TaskbarIntent.java, app/src/main/java/com/farmerbb/taskbar/fragment/AdvancedFragment.java, app/src/main/java/com/farmerbb/taskbar/service/NotificationService.java, app/src/main/java/com/farmerbb/taskbar/service/PowerMenuService.java, app/src/main/java/com/farmerbb/taskbar/ui/DashboardController.java, app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/DisableHomeReceiver.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/EnableHomeReceiver.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/ReceiveSettingsReceiver.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/SendSettingsReceiver.java, app/src/playstore/java/com/farmerbb/taskbar/receiver/TaskerActionReceiver.java
Including:
1. \*WIDGET\*.
2. \*DESKTOP\*.
3. \*ICON\*.
4. \*DASHBOARD\*.
5. TOUCH_ABSORBER_STATE_CHANGED.
6. IMPORT_FINISHED.
7. \*SETTINGS\*.
8. START/RESTART/QUIT.
9. \*HOME\*.
10. LAUNCHER_PREF_CHANGED.
11. ACCESSIBILITY_ACTION.
12. UPDATE_SWITCH.
=> Extrac left Intent action string to TaskbarIntent constants

app/build.gradle, app/src/main/java/com/farmerbb/taskbar/util/SharedPreferenceConstant.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/test/java/com/farmerbb/taskbar/util/UTest.java
Extract `SharedPreference` key used in `U.java` to `SharedPreferenceConstant.java`. And all some tests for it.
Test: ./gradlew test, and all tests passed.
=> Extract SharedPreference key to SharedPreferenceConstant

app/src/main/java/com/farmerbb/taskbar/ui/UIController.java, app/src/test/java/com/farmerbb/taskbar/ui/TestUIController.java, app/src/test/java/com/farmerbb/taskbar/ui/TestUIHostService.java, app/src/test/java/com/farmerbb/taskbar/ui/UIControllerTest.java, app/src/test/java/com/farmerbb/taskbar/ui/UIHostServiceTest.java, app/src/test/java/com/farmerbb/taskbar/ui/ViewParamsTest.java
This pr adds some unit tests for some classes in ui package, including:
1. `UIHostService`.
2. `UIController`.
3. `ViewParams`.
And there are three large files with large methods, that are difficulty to test. Maybe we should
divide those files and let them testable.
=> Add some unit tests for ui package

app/src/main/res/values-de/strings.xml
I forgot to translate some strings, I did look more down since I edited the file manually and thought all strings up there are translated. This PR improves some existing Translations, adds 2 translations I forgot last time and translates 1 string created after the creation of the last PR
=> Update some german strings

app/src/test/java/com/farmerbb/taskbar/util/UTest.java
=> Fix tests of UTest

app/src/main/java/com/farmerbb/taskbar/fragment/RecentAppsFragment.java, app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/main/java/com/farmerbb/taskbar/util/Constants.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarControllerTest.java, app/src/test/java/com/farmerbb/taskbar/util/UTest.java
1. Extract method to initialize recents search internal.
2. Extract method to initialize dashboard.
3. Set dashboard button to visible when initializing dashboard with dashboard enabled.
4. Extract `PREF_RECENTS_AMOUNT` values to constant.
=> Split TaskbarController large methods part03

app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarControllerTest.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarShadowScrollView.java
1. Extract method to scroll task in `TaskbarController`. The new method use  `TaskbarPosition.isVertical` to simplify the `switch` checking.
2. Extract method to calculate scroll view layout params in `TaskbarController`.
=> Split TaskbarController large methods part04

app/src/main/java/com/farmerbb/taskbar/activity/MainActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/ShortcutActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/StartTaskbarActivity.java, app/src/main/java/com/farmerbb/taskbar/util/Constants.java, app/src/nonlib/java/com/farmerbb/taskbar/util/ShortcutUtils.java
=> add intent extra key contants

app/src/main/java/com/farmerbb/taskbar/ui/TaskbarController.java, app/src/test/java/com/farmerbb/taskbar/mockito/StringAnswer.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarControllerTest.java
1. Extract method to check whether to need to reverse order in `TaskbarController`.
2. Extract method to filter foreground app in `TaskbarController`.
=> Split TaskbarController large methods part05

app/src/main/java/com/farmerbb/taskbar/ui/StartMenuController.java, app/src/test/java/com/farmerbb/taskbar/ui/StartMenuControllerTest.java
1.  Extract method to check shouldShowSearchBox for `StartMenuController`.
2.  Extract methods to get start menu gravity and layout id for `StartMenuController`.
=> Split StartMenuController large methods part01

app/src/main/java/com/farmerbb/taskbar/ui/StartMenuController.java, app/src/test/java/com/farmerbb/taskbar/ui/StartMenuControllerTest.java
Extract methods to generate search intent for `StartMenuController`
=> Split StartMenuController large methods part02

app/src/main/java/com/farmerbb/taskbar/ui/StartMenuController.java, app/src/test/java/com/farmerbb/taskbar/Constants.java, app/src/test/java/com/farmerbb/taskbar/shadow/TaskbarShadowLauncherApps.java, app/src/test/java/com/farmerbb/taskbar/ui/StartMenuControllerTest.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarControllerTest.java
1. Extract method to generate app entries for StartMenuController
=>  Split StartMenuController large methods part03

app/src/main/java/com/farmerbb/taskbar/activity/ContextMenuActivity.java, app/src/main/java/com/farmerbb/taskbar/activity/DashboardActivity.java, app/src/main/java/com/farmerbb/taskbar/ui/DashboardController.java, app/src/main/java/com/farmerbb/taskbar/util/Constants.java, app/src/main/java/com/farmerbb/taskbar/util/U.java, app/src/test/java/com/farmerbb/taskbar/Constants.java, app/src/test/java/com/farmerbb/taskbar/ui/DashboardControllerTest.java, app/src/test/java/com/farmerbb/taskbar/ui/StartMenuControllerTest.java, app/src/test/java/com/farmerbb/taskbar/ui/TaskbarControllerTest.java
=> Split DashboardController large methods part01

README.md, app/src/main/res/values-zh-rCN-v28/strings.xml, app/src/main/res/values-zh-rCN/strings.xml
As titled.
Thanks for the great app! Its Desktop Mode works pretty well with Sony Xpeira 1.
=> Update Chinese translation for desktop mode and a few terms.

app/src/main/java/com/farmerbb/taskbar/ui/DashboardController.java, app/src/main/java/com/farmerbb/taskbar/util/Constants.java, app/src/test/java/com/farmerbb/taskbar/Constants.java, app/src/test/java/com/farmerbb/taskbar/ui/DashboardControllerTest.java
=>  Split DashboardController large methods part02

app/src/main/java/com/farmerbb/taskbar/util/Constants.java, app/src/nonlib/java/com/farmerbb/taskbar/activity/PersistentShortcutSelectAppActivity.java, app/src/nonlib/java/com/farmerbb/taskbar/service/FavoriteAppTileService.java, app/src/test/java/com/farmerbb/taskbar/Constants.java, app/src/test/java/com/farmerbb/taskbar/service/FavoriteAppTileServiceTest.java, app/src/test/java/com/farmerbb/taskbar/shadow/TaskbarShadowTileService.java
=> Add tests for package com.farmerbb.taskbar.service part02

app/src/main/java/com/farmerbb/taskbar/service/NotificationCountService.java, app/src/test/java/com/farmerbb/taskbar/service/NotificationCountServiceTest.java
=> Add tests for NotificationCountService

app/src/test/java/com/farmerbb/taskbar/receiver/BootReceiverTest.java, app/src/test/java/com/farmerbb/taskbar/receiver/PackageUpgradeReceiverTest.java
=> Add tests for BootReceiver and PackageUpgradeReceiver

app/src/main/java/com/farmerbb/taskbar/receiver/QuitReceiver.java, app/src/main/java/com/farmerbb/taskbar/receiver/ShowHideTaskbarReceiver.java, app/src/test/java/com/farmerbb/taskbar/receiver/QuitReceiverTest.java, app/src/test/java/com/farmerbb/taskbar/receiver/ShowHideTaskbarReceiverTest.java
=> Add tests for QuitReceiver and ShowHideTaskbarReceiver

app/build.gradle
This minor version removes some logs.
=> Bump robolectric to 4.5.1

app/src/main/java/com/farmerbb/taskbar/backup/BackupUtils.java
Little refactor commit after very long time.
=> Extract backup key to constants

app/src/androidx86/java/dalvik/system/VMRuntime.java, app/src/androidx86/java/sun/misc/Unsafe.java
It will help to fix Android-x86 building.
Fix https://github.com/farmerbb/Taskbar/issues/226.
=> Add stub part of AndroidHiddenApiBypass for Android-x86
